### ISSUE TITLE
Small screen: font sizes don't seem to match guidelines

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/landscape.canonical.com#13]
The font sizes seem to big for small screen. Is it following the existing patterns?

**Comment by yaili** [comment]
Looked again. Maybe this is only the case when p.intro is used. The main problem is in the "Save time and improve security" row at the top.

**Comment by richmccartney** [comment]
@yaili resolved this now. I didn't apply my styles to the list for online desktop.
