### ISSUE TITLE
Small screen: hero layout change

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/landscape.canonical.com#14]
The pattern we follow in ubuntu.com for heros is to have the image above the text and then the text below, instead of on top of it. In this case, perhaps the text should go before the image though.

**Comment by richmccartney** [comment]
@yaili well I would say your designs imply this is more of a cover image rather than an individual image which can get effected by the layout. The hero image on both the index and features wouldn't work in this way. Can we create a new pattern for this perhaps?

**Comment by yaili** [comment]
What would that pattern be?

**Comment by richmccartney** [comment]
@yaili I feel we would need to create one as maas.io/ also has the same issue. Personally I don't think there is any problem with a background image being underneath the text.

**Comment by yaili** [comment]
It's not too bad, but the image is not really adding anything in that case.
