### ISSUE TITLE
Small screen, Try: update table

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/landscape.canonical.com#18]
Can we make the font size in the table column header smaller?

And add some padding left and right of the tablet?

Do you have any suggestions on how to improve the layout of the tabs in the table?

**Comment by richmccartney** [comment]
@yaili I've made changes to the padding and spacing. Regarding the tab view the only thing I can think of is the title goes full width so the tabs have more space. But this will be impossible as they are apart of the whole table above as per the designs.

**Comment by yaili** [comment]
It looks OK now. I'm thinking if the tab text should be orange in both, or it won't look like it's a link. But that would break the pattern… mmmm
