### ISSUE TITLE
Home hero, Get in touch link

### ISSUE THREAD

**Issue by liviathi** [ubuntudesign/landscape.canonical.com#22]
Not linked to Get in touch page.

**Comment by richmccartney** [comment]
@liviathi there isn't a design / file for the contact us page currently hence why the link will not work.

**Comment by liviathi** [comment]
@yaili could you design a form based on this copy doc? https://docs.google.com/document/d/1mfqKCz2Ftk-8U6iPTCPfwWN7zJrGBZZCSZlB5VHiLfE/edit

@pmahnke is it ok to use the same marketo form from /management?

**Comment by liviathi** [comment]
@richmccartney you can use the same pattern as the other contact us pages, here's the copy doc https://docs.google.com/document/d/1mfqKCz2Ftk-8U6iPTCPfwWN7zJrGBZZCSZlB5VHiLfE/edit

And here's the link to marketo https://pastebin.canonical.com/147417/
