### ISSUE TITLE
Home > Save time... Link does not lead anywhere

### ISSUE THREAD

**Issue by liviathi** [ubuntudesign/landscape.canonical.com#23]

**Comment by richmccartney** [comment]
@liviathi this is going to the benefits page in the google docs, as I am aware the benefits page is changing or is apart of the Features page now? Can you advise please.

**Comment by richmccartney** [comment]
@liviathi if you could follow up on this issue it would be useful thanks :)

**Comment by liviathi** [comment]
@richmccartney you're right, I removed the link on the copy docs because there's another further down the page leading to features.
