### ISSUE TITLE
Home: padding doesn't seem the same in dark strip quote row

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/landscape.canonical.com#4]
It seems there is less padding top here than on the row above, and the padding bottom seems smaller than top.

**Comment by richmccartney** [comment]
@yaili all rows have ```padding: 60px 20px 40px;``` I'm guessing we would prefer it to be set at ```60px 20px```?

**Comment by yaili** [comment]
Indeed. Unless the container inside the row compensates for the missing 20 px at the bottom

**Comment by anthonydillon** [comment]
The reason for 40px bottom is due to the grid adding 20px bottom so the
space at to and bottom are both 60px.
