### ISSUE TITLE
Home > Hero illustration > one bar is darker

### ISSUE THREAD

**Issue by liviathi** [ubuntudesign/landscape.canonical.com#52]
Image is not the right one, there should be no darker bar on the right.

**Comment by richmccartney** [comment]
@liviathi looking at @yaili designs these look correct. @yaili can you look into this please.

**Comment by liviathi** [comment]
![screen shot 2016-01-13 at 14 05 46](https://cloud.githubusercontent.com/assets/7677498/12296320/d9ff4cda-b9fe-11e5-8291-9aa0e3869b39.png)
note there is no darker bar on the right
